// app/layout.tsx
import ClientLayout from './components/ClientLayout';
import Navbar from './components/navbar';
import './globals.css';
import { Providers } from './providers';
import { getSession, SessionProvider } from 'next-auth/react';
import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async  function RootLayout({ children }) {
  const session = await getSession();

  return (
    <html lang="en">
      <body>
        <ClientLayout>
          <Navbar />
          <main>
            <Toaster/>
            {children}</main>
        </ClientLayout>
      </body>
    </html>
  );
}
